---
from: markdown+autolink_bare_uris

metadata:
  # document metadata
  title: "Command-line finances using the Plain Text Accounting ecosystem"
  subtitle: "A workshop meant to improve personal finance confidence using software skills"
  author: ["Colin Dean","@colindean"]
  subject: "Plain Text Accounting"
  keywords:
    - plain text accounting
    - ledger
    - personal finance
    - timekeeping
    - retirement
    - investing
    - trading
    - accounting
    - bookkeeping
  thanks: |
    Thank you to John Wiegley, author of Ledger, for starting a revolution
    freeing personal and business finances from the walled garden of
    proprietary software.

    Thank you to Simon Michael, author of hledger and maintainer of
    plaintextaccounting.org, for turning a single tool into an ecosystem
    with a standard.

    Thank you to my parents, who involved me in financial decisions from
    and early age and who taught me how to save, track, and do good with my money
    even when theirs was exceptionally tight.

    And lastly, thank you to you who are seeking to improve how you live your
    life. May your thirst for knowledge be quenched by this workshop, and I
    hope that you will contribute back to the Plain Text Accounting ecosystem
    by sharing your knowledge as I have shared mine.
  # filter metadata
  # crossrefYaml: pandoc-crossref.yaml

include-before-body: ['LICENSE.tex','REPO.tex']

variables:
  # physical paper and layout settings
  documentclass: report
  papersize: letter
  geometry:
    - margin=1in
  lof: true
  lot: true
  toc: true
  fontfamily: 'sourceserifpro'
  colorlinks: true
  links-as-notes: true
  # page stylings
  pagestyle: headings

#include-in-header:
#  - headers.tex

bibliography:
  - refs.bibtex

number-sections: true

pdf-engine: xelatex
filters:
  - pandoc-crossref
  - pandoc-citeproc
  - pandoc-include-code
  # - filter-pipe.lua
  - panpipe

preserve-tabs: true
